.robotcode-cache: &robotcode-cache
  key: "$CI_PROJECT_NAME-robotcode-cache-key"
  paths:
    - robotcode/*
  policy: pull

default:
  image: gradle:8.12.1-jdk21

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - preparation
  - build
  - test
  - publish

download-robotcode:
  stage: preparation
  image: python:3.11
  script:
    - mkdir -p robotcode
    - rm -rf robotcode/*.dist-info
    - pip install --upgrade -t robotcode robotcode[debugger]
    - rm -rf robotcode/robot && rm -rf robotcode/robotframework*
  cache:
    - <<: *robotcode-cache
      policy: pull-push

compile-code:
  stage: preparation
  script: gradle jarSearchableOptions

sign-plugin:
  stage: build
  script:
    - mv robotcode bundled/libs
    - gradle signPlugin
  artifacts:
    paths:
      - build/distributions/*.zip
  cache:
    - <<: *robotcode-cache

verify-plugin:
  stage: test
  script: gradle verifyPlugin

#publish-plugin:
#  stage: publish
#  rules:
#    - if: $CI_COMMIT_REF_NAME == "main"
#  script:
#    - gradle publishPlugin
#  cache:
#    - <<: *robotcode-cache
