name: Build
on:
  # Trigger the workflow on pushes to only the 'master' branch (this avoids duplicate checks being run, e.g., for dependabot pull requests)
  push:
    branches: [ 'main' ]
    paths-ignore: [ '**.md' ]
  # Trigger the workflow on any pull request
  pull_request:
    paths-ignore: [ '**.md' ]

jobs:

  gradleValidation:
    name: Gradle Validation
    uses: ./.github/workflows/reusable-gradleValidation.yml

  unitTests:
    name: Unit Tests
    needs: gradleValidation
    uses: ./.github/workflows/reusable-unitTests.yml
    secrets: inherit
    permissions:
      checks: write

  integrationTests:
    name: Integration Tests
    needs: [ gradleValidation, unitTests ]
    uses: ./.github/workflows/reusable-integrationTests.yml
    secrets: inherit

  #  integrationTestsEAP:
  #    name: Integration Tests EAP
  #    needs: gradleValidation
  #    uses: ./.github/workflows/reusable-integrationTests.yml
  #    secrets: inherit
  #    with:
  #      platformVersion: 222-EAP-SNAPSHOT

  codeInspection:
    name: Code Inspection
    needs: integrationTests
    uses: ./.github/workflows/reusable-codeInspection.yml

  build:
    name: Build
    needs:
      - unitTests
      - integrationTests
    # - integrationTestsEAP
      - codeInspection
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: jetbrains
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Set environment variables
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
          NAME="$(echo "$PROPERTIES" | grep "^name:" | cut -f2- -d ' ')"
          ARTIFACT="$NAME-$VERSION.zip"
          CHANGELOG="$(./gradlew getChangelog --unreleased --no-header --console=plain -q)"
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "artifact=$ARTIFACT" >> $GITHUB_OUTPUT

          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Download RobotCode Debugger
        shell: bash
        run: |
          mkdir -p bundled/libs
          pip install --upgrade -t bundled/libs robotcode[debugger]
          rm -rf bundled/libs/robot && rm -rf bundled/libs/robotframework*

      - name: Build Plugin
        run: ./gradlew buildPlugin -x test

      # Store an already-built plugin as an artifact for downloading
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.properties.outputs.artifact }}
          path: ./build/distributions/${{ steps.properties.outputs.artifact }}

  # Prepare a draft release for GitHub Releases page for the manual verification
  # If accepted and published, the release workflow would be triggered
  releaseDraft:
    name: Release Draft
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:

      # Check out the current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Remove old release drafts by using the curl request for the available releases with a draft flag
      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/{owner}/{repo}/releases \
            --jq '.[] | select(.draft == true) | .id' | xargs -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}

      # Create a new release draft which is not publicly visible and requires manual acceptance
      - name: Create Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ needs.build.outputs.version }} \
            --draft \
            --title "${{ needs.build.outputs.version }}" \
            --notes "$(cat << 'EOM'
          ${{ needs.build.outputs.changelog }}
          EOM
          )"
